extensions:
  - id: ci
    directory: ci_extension
    variables:
      myVariable:
        value: "Hello World"
        type: literal
      myNumber:
        value: 0
        type: literal
  - id: agxx
    directory: tww2ag6496
    variables: {}