name: Check for changes in stable datamodel versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - datamodel/changelogs/**
      - '.github/workflows/check-changes-in-changelog.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get lastest stable release
        run: |
          LATEST_STABLE_RELEASE=$(gh api repos/teksi/wastewater/releases/latest --jq '.tag_name')
          echo "LATEST_STABLE_RELEASE=$LATEST_STABLE_RELEASE" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}

      - name: Check for changes in the specified folders
        run: |
          CHANGED_FILES=${{ steps.changed-files.outputs.all_changed_files }}
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == datamodel/changelogs/* ]]; then
              VERSION_FOLDER=$(echo $FILE | cut -d'/' -f3)
              if printf '%s\n' "$LATEST_STABLE_RELEASE" "$VERSION_FOLDER" | sort -V | head -n1 | grep -q "$VERSION_FOLDER"; then
                echo "Changes detected in a disallowed datamodel/changelogs/$VERSION_FOLDER folder."
                exit 1
              fi
            fi
          done
          echo "No changes detected in disallowed datamodel/changelogs version folders."
