name: Test and build Docker image

on:
  push:
    branches:
      - master
    paths:
      - datamodel
      - '.github/workflows/create-dumps.yml'
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  docker-tests:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "build dockerfile"
        run:  docker build -f datamodel/.docker/Dockerfile --tag teksi/wastewater:unstable .

      - name: "initialize container"
        run: |
          docker run -d -p 5432:5432 --name tww teksi/wastewater:unstable
          docker exec tww init_db.sh wait

      - name: create dumps
        run: docker exec -e PGSERVICE=pg_teksi_wastewater tww /src/scripts/create-dumps.py
